# Generated by Django 5.1.2 on 2024-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
